home_title: zylon.tk Home
docs_title: zylon.tk Documentation
motto: We're a server network where everyone has the ability to explore and create new things.
description: We're a server network where everyone has the ability to explore and create new things.
forum_link: https://forum.zylon.tk
guild_link: https://ptb.discordapp.com/invite/bDzFtE
github_link: https://github.com/zylontk
1a:
1b:
1c:
2a:
2b:
3a:
3b:
3c:
4a:
4b:
4c:
